# Generated by Django 3.0.5 on 2020-04-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
